In [4]:
import numpy as np
import time 

size = 10_000_000
py_list = list(range(size))
start = time.time()
sq_list =[x**2 for x in py_list]
end =  time.time()
print(f"Total time to py_list run is {end - start}second .")

np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2
end = time.time()
print(f"Total time to np_array run is {end - start}second .")

Total time to py_list run is 0.2706451416015625second .
Total time to np_array run is 0.030538082122802734second .


In [5]:
# Create Array 
# Create 1D Array 
arr = np.array([1,2,3,4,5,6])
print(arr , type(arr) , arr.shape)

arr2 = np.array([1,2,3,4,"name"])
print(arr2 , type(arr2) , arr2.shape)

#Create 2D array 
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,type(arr2D),arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> (6,)
['1' '2' '3' '4' 'name'] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [6]:
#Opration on Array 
#The create Zero array 
arr = np.zeros((3,3),dtype = "int64")
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
#Print 1 in All matrix or Array 
arr = np.ones((3,3),dtype = "int64")
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
#print any one number in all Matrix or Array 
arr = np.full((3,3),2)
print(arr)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [9]:
#print To 1 in eye form
arr = np.eye(4)
int_con = arr.astype(np.int64)
print(int_con , int_con.dtype)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] int64


In [10]:
#Print to for loop as the Matrix or array 
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
#Print to for loop but how  many print value .
arr = np.linspace(0 ,100 , 5 ,dtype = "int64")
print(arr)

[  0  25  50  75 100]


In [21]:
#Opretion on Array 

arr =  np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshape = arr.reshape((3,2))
print(reshape , reshape.reshape) 

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] <built-in method reshape of numpy.ndarray object at 0x11111f510>


In [31]:
# List VS Array copy 

lis  =   [ 1,2,3,4, ]
print(lis)
sub_lis = lis[1:3]
print(sub_lis)
sub_lis [0] = 200
print(sub_lis)
print(lis)

arr = np.array([1,2,3,4,5,6])
print(arr)
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[1] =  200 
print(sub_arr)
print(arr)


[1, 2, 3, 4]
[2, 3]
[200, 3]
[1, 2, 3, 4]
[1 2 3 4 5 6]
[2 3]
[  2 200]
[  1   2 200   4   5   6]


In [61]:
# Multi Dimentions 
# 2D Array 

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)
print(np.sum(arr2D))
sum_of_col = np.sum(arr2D , axis = 0)
print(f"The Sum of the Col number  is {sum_of_col}")

sum_of_row = np.sum(arr2D , axis = 1)
print(f"The aum of the rows is {sum_of_row}")

print(arr2D[0:2,2:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
45
The Sum of the Col number  is [12 15 18]
The aum of the rows is [ 6 15 24]
[[3]
 [6]]


In [80]:
# 3D Array 

arr = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr , arr.shape)

#indexing 
print(arr[0,2,0])

#slicing 
print("----------")
print(arr[0,0:2,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
5
----------
[1 3]


In [88]:
# normalization 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr , arr.shape)

#std normalization 
mean =  np.mean(arr)
std_dev =  np.std(arr)
print("----------")
print(f"This is a MEAN value \n {mean} ")
print("----------")
print(f"This is a Std devrivtion \n {std_dev}")
print("----------")
print(f"The Normlization of the array is \n  {(arr - mean)/std_dev} .")
print("----------")


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
----------
This is a MEAN value 
 5.0 
----------
This is a Std devrivtion 
 2.581988897471611
----------
The Normlization of the array is 
  [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]] .
----------
